[package]
name                   = "nixos-core"
version.workspace      = true
edition.workspace      = true
rust-version.workspace = true
license.workspace      = true
repository.workspace   = true
description            = "Core NixOS system utilities"

# Multi-call binary symlinks will be created for each enabled feature
[features]
default             = [ "update-users-groups", "setup-etc", "init-script", "persistence", "stage-1", "stage-2" ]
init-script         = [ "dep:init-script" ]
persistence         = [ "dep:persistence" ]
setup-etc           = [ "dep:setup-etc" ]
stage-1             = [ "dep:stage1" ]
stage-2             = [ "dep:stage2" ]
update-users-groups = [ "dep:update-users-groups" ]

[dependencies]
init-script         = { workspace = true, optional = true }
persistence         = { workspace = true, optional = true }
setup-etc           = { workspace = true, optional = true }
stage1              = { workspace = true, optional = true }
stage2              = { workspace = true, optional = true }
update-users-groups = { workspace = true, optional = true }

anyhow.workspace     = true
env_logger.workspace = true
log.workspace        = true

[dev-dependencies]
tempfile.workspace = true
