use std::{
  collections::HashSet,
  ffi::{CString, OsStr, OsString},
  fs::{self, FileType},
  os::{
    fd::{AsRawFd, OwnedFd},
    unix::{ffi::OsStrExt, fs::MetadataExt},
  },
  path::{Component, Path, PathBuf},
};

use anyhow::{Context, Result, bail, ensure};
use clap::Parser;
use log::info;
use nix::{
  errno::Errno,
  fcntl::{OFlag, open, openat, renameat},
  mount::{MntFlags, MsFlags, mount, umount2},
  sys::stat::{Mode, fchmod, mkdirat},
  unistd::{Gid, Group, Uid, UnlinkatFlags, User, fchown, symlinkat, unlinkat},
};
use serde::{Deserialize, Serialize};

#[derive(Parser, Debug)]
#[command(
  name = "persist",
  about = "Project persistent files and directories into a root"
)]
struct Args {
  /// JSON persistence plan generated by the NixOS module.
  plan:    PathBuf,
  /// Root containing the plan's absolute source and target paths.
  #[arg(long, default_value = "/")]
  root:    PathBuf,
  /// Remove every projection recorded in the runtime state.
  #[arg(long)]
  clear:   bool,
  /// Validate and report the plan without changing the filesystem.
  #[arg(long)]
  dry_run: bool,
}

#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
struct Plan {
  version: u8,
  entries: Vec<Entry>,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
struct Entry {
  store:        PathBuf,
  source:       PathBuf,
  target:       PathBuf,
  kind:         Kind,
  method:       Method,
  #[serde(default)]
  owner:        Option<String>,
  #[serde(default)]
  group:        Option<String>,
  #[serde(default)]
  mode:         Option<String>,
  #[serde(default)]
  parent_owner: Option<String>,
  #[serde(default)]
  parent_group: Option<String>,
  #[serde(default)]
  parent_mode:  Option<String>,
}

#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "lowercase")]
enum Kind {
  Directory,
  File,
}

#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "lowercase")]
enum Method {
  Bind,
  Symlink,
}

#[derive(Debug, Default, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
struct RuntimeState {
  version: u8,
  entries: Vec<Entry>,
}

struct Root {
  fd: OwnedFd,
}

struct Node {
  fd:     OwnedFd,
  parent: OwnedFd,
}

pub fn run(args: &[String]) -> Result<()> {
  let args = Args::parse_from(args);
  ensure!(
    args.root.is_absolute(),
    "Root {} is not absolute",
    args.root.display()
  );
  let root = Root::open(&args.root)?;
  let dry_run = args.dry_run
    || std::env::var("NIXOS_ACTION").is_ok_and(|value| value == "dry-activate");
  let raw = fs::read(&args.plan)
    .with_context(|| format!("Failed to read {}", args.plan.display()))?;
  let mut plan: Plan = serde_json::from_slice(&raw)
    .with_context(|| format!("Failed to parse {}", args.plan.display()))?;
  ensure!(
    plan.version == 1,
    "Unsupported persistence plan version {}",
    plan.version
  );
  validate_and_sort(&mut plan.entries)?;

  let state_path = Path::new("/run/nixos-core/persistence.json");
  let current = if args.clear { &[][..] } else { &plan.entries };
  let previous = read_state(&root, state_path)?;

  preflight(&root, &previous.entries, current)?;

  if dry_run {
    for entry in current {
      info!(
        "would project {} at {}",
        entry.source.display(),
        entry.target.display()
      );
    }
    for entry in stale_entries(&previous.entries, current) {
      info!("would remove projection at {}", entry.target.display());
    }
    return Ok(());
  }

  prepare(&root, current)?;
  if let Err(error) = reconcile(&root, &previous.entries, current) {
    activate(&root, &previous.entries, &mut Vec::new())
      .context("Failed to restore the previous persistence plan")?;
    return Err(error);
  }
  let mut activated = Vec::new();
  if let Err(error) = activate(&root, current, &mut activated) {
    restore(&root, &previous.entries, &activated)
      .context("Failed to restore the previous persistence plan")?;
    return Err(error);
  }
  if let Err(error) = write_state(&root, state_path, current) {
    restore(&root, &previous.entries, &activated)
      .context("Failed to restore the previous persistence plan")?;
    return Err(error);
  }
  Ok(())
}

fn validate_and_sort(entries: &mut [Entry]) -> Result<()> {
  let mut sources = HashSet::new();
  let mut targets = HashSet::new();
  let stores = entries
    .iter()
    .map(|entry| &entry.store)
    .collect::<HashSet<_>>();

  for entry in entries.iter() {
    validate_absolute(&entry.store, "store")?;
    validate_absolute(&entry.source, "source")?;
    validate_absolute(&entry.target, "target")?;
    ensure!(
      entry.store != Path::new("/"),
      "The persistence store cannot be /"
    );
    ensure!(
      entry.target != Path::new("/"),
      "The persistence target cannot be /"
    );
    ensure!(
      entry.source.starts_with(&entry.store) && entry.source != entry.store,
      "Source {} is not below store {}",
      entry.source.display(),
      entry.store.display()
    );
    ensure!(
      sources.insert(&entry.source),
      "Duplicate source {}",
      entry.source.display()
    );
    ensure!(
      targets.insert(&entry.target),
      "Duplicate target {}",
      entry.target.display()
    );
    for store in &stores {
      ensure!(
        !paths_overlap(&entry.target, store),
        "Persistence target {} overlaps store {}",
        entry.target.display(),
        store.display()
      );
    }
    for mode in [entry.mode.as_deref(), entry.parent_mode.as_deref()]
      .into_iter()
      .flatten()
    {
      parse_mode(mode)?;
    }
  }

  for parent in entries
    .iter()
    .filter(|entry| entry.method == Method::Symlink)
  {
    if let Some(child) = entries.iter().find(|entry| {
      entry.target != parent.target && entry.target.starts_with(&parent.target)
    }) {
      bail!(
        "Target {} is nested below symlink target {}",
        child.target.display(),
        parent.target.display()
      );
    }
  }

  entries.sort_by(|left, right| {
    left
      .target
      .components()
      .count()
      .cmp(&right.target.components().count())
      .then_with(|| left.target.cmp(&right.target))
  });
  Ok(())
}

fn paths_overlap(left: &Path, right: &Path) -> bool {
  left.starts_with(right) || right.starts_with(left)
}

fn validate_absolute(path: &Path, label: &str) -> Result<()> {
  ensure!(
    path.is_absolute(),
    "{label} path {} is not absolute",
    path.display()
  );
  ensure!(
    path
      .components()
      .all(|part| matches!(part, Component::RootDir | Component::Normal(_))),
    "{label} path {} is not normalized",
    path.display()
  );
  Ok(())
}

fn preflight(root: &Root, previous: &[Entry], current: &[Entry]) -> Result<()> {
  for entry in current {
    let store = root
      .open_node(&entry.store, Kind::Directory, false)?
      .with_context(|| {
        format!("Persistence store {} does not exist", entry.store.display())
      })?;
    ensure!(
      is_mount_node(&store),
      "Persistence store {} is not mounted",
      entry.store.display()
    );

    root.inspect_node(&entry.source, entry.kind, "source")?;
    match entry.method {
      Method::Bind => {
        if let Some(target) =
          root.inspect_node(&entry.target, entry.kind, "target")?
          && is_mount_node(&target)
        {
          let source = root
            .open_node(&entry.source, entry.kind, false)?
            .with_context(|| {
              format!("Source {} disappeared", entry.source.display())
            })?;
          ensure!(
            same_node(&source, &target)?,
            "Target {} is already a different mount",
            entry.target.display()
          );
        }
      },
      Method::Symlink => inspect_link(root, entry)?,
    }
    resolve_metadata(entry)?;
  }
  for entry in stale_entries(previous, current) {
    preflight_removal(root, entry)?;
  }
  Ok(())
}

fn prepare(root: &Root, entries: &[Entry]) -> Result<()> {
  for entry in entries {
    let source_parent = root.ensure_parent(&entry.source)?;
    apply_parent_metadata(entry, &source_parent, &entry.source)?;
    let source = root.create_node(&entry.source, entry.kind, "source")?;
    apply_entry_metadata(entry, &source.fd)?;

    let target_parent = root.ensure_parent(&entry.target)?;
    apply_parent_metadata(entry, &target_parent, &entry.target)?;
    if entry.method == Method::Bind {
      root.create_node(&entry.target, entry.kind, "target")?;
    }
  }
  Ok(())
}

fn activate(
  root: &Root,
  entries: &[Entry],
  activated: &mut Vec<Entry>,
) -> Result<()> {
  for entry in entries {
    let changed = match entry.method {
      Method::Bind => bind(root, entry)?,
      Method::Symlink => link(root, entry)?,
    };
    if changed {
      activated.push(entry.clone());
    }
  }
  Ok(())
}

fn restore(root: &Root, previous: &[Entry], activated: &[Entry]) -> Result<()> {
  reconcile(root, activated, &[])?;
  activate(root, previous, &mut Vec::new())
}

fn read_state(root: &Root, path: &Path) -> Result<RuntimeState> {
  let Some(node) = root.open_node(path, Kind::File, false)? else {
    return Ok(RuntimeState {
      version: 1,
      entries: Vec::new(),
    });
  };
  let raw = fs::read(proc_path(&node.fd)).with_context(|| {
    format!("Failed to read runtime state {}", path.display())
  })?;
  let mut state: RuntimeState =
    serde_json::from_slice(&raw).with_context(|| {
      format!("Failed to parse runtime state {}", path.display())
    })?;
  ensure!(
    state.version == 1,
    "Unsupported persistence runtime state version {}",
    state.version
  );
  validate_and_sort(&mut state.entries)?;
  Ok(state)
}

fn stale_entries<'a>(
  previous: &'a [Entry],
  current: &[Entry],
) -> Vec<&'a Entry> {
  previous
    .iter()
    .filter(|old| !current.iter().any(|new| same_projection(old, new)))
    .collect()
}

fn reconcile(root: &Root, previous: &[Entry], current: &[Entry]) -> Result<()> {
  let mut stale = stale_entries(previous, current);
  stale
    .sort_by_key(|entry| std::cmp::Reverse(entry.target.components().count()));
  for entry in stale {
    match entry.method {
      Method::Bind => remove_bind(root, entry)?,
      Method::Symlink => remove_owned_symlink(root, entry)?,
    }
  }
  Ok(())
}

fn preflight_removal(root: &Root, entry: &Entry) -> Result<()> {
  if entry.method != Method::Bind {
    return inspect_link(root, entry);
  }
  let Some(target) = root.open_node(&entry.target, entry.kind, false)? else {
    return Ok(());
  };
  if !is_mount_node(&target) {
    return Ok(());
  }
  verify_projection_source(root, entry, &target)?;
  Ok(())
}

fn remove_bind(root: &Root, entry: &Entry) -> Result<()> {
  let Some(target) = root.open_node(&entry.target, entry.kind, false)? else {
    return Ok(());
  };
  if !is_mount_node(&target) {
    return Ok(());
  }
  verify_projection_source(root, entry, &target)?;
  let Node { fd, parent } = target;
  drop(fd);
  let target_path = proc_path(&parent).join(file_name(&entry.target)?);
  umount2(&target_path, MntFlags::empty()).with_context(|| {
    format!(
      "Failed to unmount stale projection {}",
      entry.target.display()
    )
  })
}

fn verify_projection_source(
  root: &Root,
  entry: &Entry,
  target: &Node,
) -> Result<()> {
  let source = root
    .open_node(&entry.source, entry.kind, false)?
    .with_context(|| {
      format!("Cannot verify stale bind source {}", entry.source.display())
    })?;
  ensure!(
    same_node(&source, target)?,
    "Refusing to unmount {} because it no longer resolves to {}",
    entry.target.display(),
    entry.source.display()
  );
  Ok(())
}

fn same_projection(left: &Entry, right: &Entry) -> bool {
  left.source == right.source
    && left.target == right.target
    && left.kind == right.kind
    && left.method == right.method
}

fn is_mount_node(node: &Node) -> bool {
  match (mount_id(&node.fd), mount_id(&node.parent)) {
    (Some(node_id), Some(parent_id)) if node_id != parent_id => true,
    _ => {
      match (metadata_fd(&node.fd), metadata_fd(&node.parent)) {
        (Ok(node_metadata), Ok(parent_metadata)) => {
          node_metadata.dev() != parent_metadata.dev()
        },
        _ => false,
      }
    },
  }
}

fn mount_id(fd: &OwnedFd) -> Option<u64> {
  let fdinfo =
    fs::read_to_string(format!("/proc/self/fdinfo/{}", fd.as_raw_fd())).ok()?;
  fdinfo
    .lines()
    .find_map(|line| line.strip_prefix("mnt_id:\t")?.parse().ok())
}

fn inspect_link(root: &Root, entry: &Entry) -> Result<()> {
  let Some((parent, name)) = root.existing_parent_and_name(&entry.target)?
  else {
    return Ok(());
  };
  let path = proc_path(&parent).join(&name);
  match fs::symlink_metadata(&path) {
    Ok(metadata) if metadata.file_type().is_symlink() => {
      let existing = fs::read_link(&path).with_context(|| {
        format!("Failed to read {}", entry.target.display())
      })?;
      ensure!(
        existing == entry.source,
        "Symlink {} points to {}, expected {}",
        entry.target.display(),
        existing.display(),
        entry.source.display()
      );
      Ok(())
    },
    Ok(_) => {
      bail!(
        "Refusing to replace existing target {} with a symlink",
        entry.target.display()
      )
    },
    Err(error) if error.kind() == std::io::ErrorKind::NotFound => Ok(()),
    Err(error) => {
      Err(error).with_context(|| {
        format!("Failed to inspect {}", entry.target.display())
      })
    },
  }
}

fn remove_owned_symlink(root: &Root, entry: &Entry) -> Result<()> {
  let Some((parent, name)) = root.existing_parent_and_name(&entry.target)?
  else {
    return Ok(());
  };
  let path = proc_path(&parent).join(&name);
  let existing = match fs::read_link(&path) {
    Ok(existing) => existing,
    Err(error)
      if matches!(
        error.kind(),
        std::io::ErrorKind::NotFound | std::io::ErrorKind::InvalidInput
      ) =>
    {
      return Ok(());
    },
    Err(error) => {
      return Err(error).with_context(|| {
        format!("Failed to inspect {}", entry.target.display())
      });
    },
  };
  if existing != entry.source {
    return Ok(());
  }

  let quarantine = OsString::from(format!(
    ".nixos-core-stale-{}-{}",
    std::process::id(),
    name.to_string_lossy()
  ));
  rename_noreplace(&parent, Path::new(&name), &parent, Path::new(&quarantine))
    .with_context(|| {
      format!(
        "Failed to quarantine stale symlink {}",
        entry.target.display()
      )
    })?;
  let quarantined = proc_path(&parent).join(&quarantine);
  match fs::read_link(&quarantined) {
    Ok(source) if source == entry.source => {
      unlinkat(&parent, Path::new(&quarantine), UnlinkatFlags::NoRemoveDir)
        .with_context(|| {
          format!("Failed to remove stale symlink {}", entry.target.display())
        })
    },
    result => {
      rename_noreplace(
        &parent,
        Path::new(&quarantine),
        &parent,
        Path::new(&name),
      )
      .with_context(|| {
        format!(
          "Target {} changed while it was being reconciled",
          entry.target.display()
        )
      })?;
      match result {
        Ok(_) => {
          bail!(
            "Target {} changed while it was being reconciled",
            entry.target.display()
          )
        },
        Err(error) => {
          Err(error).with_context(|| {
            format!("Failed to inspect {}", entry.target.display())
          })
        },
      }
    },
  }
}

fn write_state(root: &Root, path: &Path, entries: &[Entry]) -> Result<()> {
  let parent = root.ensure_parent(path)?;
  let name = file_name(path)?;
  let temporary = OsString::from(format!("{}.new", name.to_string_lossy()));
  let raw = serde_json::to_vec(&RuntimeState {
    version: 1,
    entries: entries.to_vec(),
  })
  .context("Failed to serialize persistence runtime state")?;
  fs::write(proc_path(&parent).join(&temporary), raw).with_context(|| {
    format!(
      "Failed to write temporary runtime state for {}",
      path.display()
    )
  })?;
  renameat(&parent, Path::new(&temporary), &parent, Path::new(&name))
    .with_context(|| {
      format!("Failed to commit runtime state {}", path.display())
    })
}

fn rename_noreplace(
  old_parent: &OwnedFd,
  old_name: &Path,
  new_parent: &OwnedFd,
  new_name: &Path,
) -> Result<()> {
  let old_name = CString::new(old_name.as_os_str().as_bytes())
    .context("Old rename path contains a NUL byte")?;
  let new_name = CString::new(new_name.as_os_str().as_bytes())
    .context("New rename path contains a NUL byte")?;
  // SAFETY: both path pointers are live NUL-terminated strings, and both file
  // descriptors remain owned for the duration of the syscall.
  let result = unsafe {
    libc::syscall(
      libc::SYS_renameat2,
      old_parent.as_raw_fd(),
      old_name.as_ptr(),
      new_parent.as_raw_fd(),
      new_name.as_ptr(),
      libc::RENAME_NOREPLACE,
    )
  };
  Errno::result(result).map(drop).map_err(Into::into)
}

fn resolve_metadata(entry: &Entry) -> Result<()> {
  for value in [entry.owner.as_deref(), entry.parent_owner.as_deref()] {
    resolve_user(value)?;
  }
  for value in [entry.group.as_deref(), entry.parent_group.as_deref()] {
    resolve_group(value)?;
  }
  Ok(())
}

fn apply_entry_metadata(entry: &Entry, fd: &OwnedFd) -> Result<()> {
  apply_metadata(
    fd,
    entry.owner.as_deref(),
    entry.group.as_deref(),
    entry.mode.as_deref(),
    &entry.source,
  )
}

fn apply_parent_metadata(
  entry: &Entry,
  fd: &OwnedFd,
  path: &Path,
) -> Result<()> {
  apply_metadata(
    fd,
    entry.parent_owner.as_deref(),
    entry.parent_group.as_deref(),
    entry.parent_mode.as_deref(),
    path.parent().expect("validated path has a parent"),
  )
}

fn apply_metadata(
  fd: &OwnedFd,
  owner: Option<&str>,
  group: Option<&str>,
  mode: Option<&str>,
  display_path: &Path,
) -> Result<()> {
  let uid = resolve_user(owner)?.map(Uid::from_raw);
  let gid = resolve_group(group)?.map(Gid::from_raw);
  if uid.is_some() || gid.is_some() {
    fchown(fd, uid, gid)
      .with_context(|| format!("Failed to chown {}", display_path.display()))?;
  }
  if let Some(mode) = mode {
    fchmod(fd, Mode::from_bits_truncate(parse_mode(mode)?))
      .with_context(|| format!("Failed to chmod {}", display_path.display()))?;
  }
  Ok(())
}

fn parse_mode(mode: &str) -> Result<u32> {
  let parsed = u32::from_str_radix(mode, 8)
    .with_context(|| format!("Invalid octal mode {mode:?}"))?;
  ensure!(parsed <= 0o7777, "Mode {mode:?} exceeds 07777");
  Ok(parsed)
}

fn resolve_user(value: Option<&str>) -> Result<Option<u32>> {
  let Some(value) = value else { return Ok(None) };
  if let Ok(id) = value.parse() {
    return Ok(Some(id));
  }
  let user = User::from_name(value)
    .with_context(|| format!("Failed to resolve user {value}"))?;
  match user {
    Some(user) => Ok(Some(user.uid.as_raw())),
    None => bail!("User {value} does not exist"),
  }
}

fn resolve_group(value: Option<&str>) -> Result<Option<u32>> {
  let Some(value) = value else { return Ok(None) };
  if let Ok(id) = value.parse() {
    return Ok(Some(id));
  }
  let group = Group::from_name(value)
    .with_context(|| format!("Failed to resolve group {value}"))?;
  match group {
    Some(group) => Ok(Some(group.gid.as_raw())),
    None => bail!("Group {value} does not exist"),
  }
}

fn bind(root: &Root, entry: &Entry) -> Result<bool> {
  let source = root
    .open_node(&entry.source, entry.kind, false)?
    .with_context(|| {
      format!("Source {} disappeared", entry.source.display())
    })?;
  let target = root
    .open_node(&entry.target, entry.kind, false)?
    .with_context(|| {
      format!("Target {} disappeared", entry.target.display())
    })?;
  if same_node(&source, &target)? {
    return Ok(false);
  }
  ensure!(
    !is_mount_node(&target),
    "Target {} is already a different mount",
    entry.target.display()
  );
  let source_path = proc_path(&source.fd);
  let target_path = proc_path(&target.fd);
  mount(
    Some(source_path.as_path()),
    target_path.as_path(),
    None::<&str>,
    MsFlags::MS_BIND,
    None::<&str>,
  )
  .with_context(|| {
    format!(
      "Failed to bind {} at {}",
      entry.source.display(),
      entry.target.display()
    )
  })?;
  let mounted = root
    .open_node(&entry.target, entry.kind, false)?
    .with_context(|| {
      format!("Target {} disappeared after mount", entry.target.display())
    })?;
  ensure!(
    same_node(&source, &mounted)?,
    "Bind mount at {} did not resolve to {}",
    entry.target.display(),
    entry.source.display()
  );
  Ok(true)
}

fn same_node(source: &Node, target: &Node) -> Result<bool> {
  let source = metadata_fd(&source.fd)?;
  let target = metadata_fd(&target.fd)?;
  Ok(source.dev() == target.dev() && source.ino() == target.ino())
}

fn link(root: &Root, entry: &Entry) -> Result<bool> {
  let parent = root.ensure_parent(&entry.target)?;
  let name = file_name(&entry.target)?;
  let path = proc_path(&parent).join(&name);
  match fs::symlink_metadata(&path) {
    Ok(metadata) if metadata.file_type().is_symlink() => {
      let existing = fs::read_link(&path).with_context(|| {
        format!("Failed to read {}", entry.target.display())
      })?;
      ensure!(
        existing == entry.source,
        "Symlink {} points to {}, expected {}",
        entry.target.display(),
        existing.display(),
        entry.source.display()
      );
      Ok(false)
    },
    Ok(_) => {
      bail!(
        "Refusing to replace existing target {} with a symlink",
        entry.target.display()
      )
    },
    Err(error) if error.kind() == std::io::ErrorKind::NotFound => {
      symlinkat(&entry.source, &parent, Path::new(&name)).with_context(
        || {
          format!(
            "Failed to link {} to {}",
            entry.target.display(),
            entry.source.display()
          )
        },
      )?;
      Ok(true)
    },
    Err(error) => {
      Err(error).with_context(|| {
        format!("Failed to inspect {}", entry.target.display())
      })
    },
  }
}

impl Root {
  fn open(path: &Path) -> Result<Self> {
    let fd = open(
      path,
      OFlag::O_RDONLY | OFlag::O_DIRECTORY | OFlag::O_CLOEXEC,
      Mode::empty(),
    )
    .with_context(|| format!("Failed to open root {}", path.display()))?;
    Ok(Self { fd })
  }

  fn inspect_node(
    &self,
    path: &Path,
    kind: Kind,
    label: &str,
  ) -> Result<Option<Node>> {
    let node = self.open_node(path, kind, false)?;
    if let Some(node) = &node {
      ensure_kind(path, metadata_fd(&node.fd)?.file_type(), kind, label)?;
    }
    Ok(node)
  }

  fn create_node(&self, path: &Path, kind: Kind, label: &str) -> Result<Node> {
    if let Some(node) = self.open_node(path, kind, false)? {
      ensure_kind(path, metadata_fd(&node.fd)?.file_type(), kind, label)?;
      return Ok(node);
    }
    let parent_path = path.parent().expect("validated path has a parent");
    let parent = self
      .open_dir(parent_path, true)?
      .expect("create opens parent");
    let name = file_name(path)?;
    match kind {
      Kind::Directory => {
        mkdirat(&parent, Path::new(&name), Mode::from_bits_truncate(0o755))
      },
      Kind::File => {
        openat(
          &parent,
          Path::new(&name),
          OFlag::O_RDONLY
            | OFlag::O_CREAT
            | OFlag::O_EXCL
            | OFlag::O_NOFOLLOW
            | OFlag::O_CLOEXEC,
          Mode::from_bits_truncate(0o600),
        )
        .map(drop)
      },
    }
    .with_context(|| format!("Failed to create {label} {}", path.display()))?;
    self.open_node(path, kind, false)?.with_context(|| {
      format!("Created {label} {} disappeared", path.display())
    })
  }

  fn open_node(
    &self,
    path: &Path,
    kind: Kind,
    create_parent: bool,
  ) -> Result<Option<Node>> {
    let parent_path = path.parent().expect("validated path has a parent");
    let Some(parent) = self.open_dir(parent_path, create_parent)? else {
      return Ok(None);
    };
    let name = file_name(path)?;
    let mut flags = OFlag::O_RDONLY | OFlag::O_NOFOLLOW | OFlag::O_CLOEXEC;
    if kind == Kind::Directory {
      flags |= OFlag::O_DIRECTORY;
    }
    match openat(&parent, Path::new(&name), flags, Mode::empty()) {
      Ok(fd) => Ok(Some(Node { fd, parent })),
      Err(Errno::ENOENT) => Ok(None),
      Err(error) => {
        Err(error).with_context(|| {
          format!(
            "Failed to open {} without following symlinks",
            path.display()
          )
        })
      },
    }
  }

  fn ensure_parent(&self, path: &Path) -> Result<OwnedFd> {
    let parent = path.parent().expect("validated path has a parent");
    self
      .open_dir(parent, true)?
      .with_context(|| format!("Failed to create parent {}", parent.display()))
  }

  fn existing_parent_and_name(
    &self,
    path: &Path,
  ) -> Result<Option<(OwnedFd, OsString)>> {
    let parent = path.parent().expect("validated path has a parent");
    Ok(self.open_dir(parent, false)?.map(|fd| {
      (
        fd,
        file_name(path).expect("validated path has a final component"),
      )
    }))
  }

  fn open_dir(&self, path: &Path, create: bool) -> Result<Option<OwnedFd>> {
    let mut current = self
      .fd
      .try_clone()
      .context("Failed to duplicate root descriptor")?;
    for component in path.components() {
      let Component::Normal(name) = component else {
        continue;
      };
      let flags = OFlag::O_RDONLY
        | OFlag::O_DIRECTORY
        | OFlag::O_NOFOLLOW
        | OFlag::O_CLOEXEC;
      match openat(&current, Path::new(name), flags, Mode::empty()) {
        Ok(next) => current = next,
        Err(Errno::ENOENT) if create => {
          match mkdirat(
            &current,
            Path::new(name),
            Mode::from_bits_truncate(0o755),
          ) {
            Ok(()) | Err(Errno::EEXIST) => {},
            Err(error) => {
              return Err(error).with_context(|| {
                format!("Failed to create {}", path.display())
              });
            },
          }
          current = openat(&current, Path::new(name), flags, Mode::empty())
            .with_context(|| {
              format!(
                "Failed to open newly created directory {}",
                path.display()
              )
            })?;
        },
        Err(Errno::ENOENT) => return Ok(None),
        Err(error) => {
          return Err(error).with_context(|| {
            format!(
              "Failed to traverse {} without following symlinks",
              path.display()
            )
          });
        },
      }
    }
    Ok(Some(current))
  }
}

fn ensure_kind(
  path: &Path,
  file_type: FileType,
  kind: Kind,
  label: &str,
) -> Result<()> {
  let matches = match kind {
    Kind::Directory => file_type.is_dir(),
    Kind::File => file_type.is_file(),
  };
  ensure!(
    matches,
    "Existing {label} {} has the wrong type",
    path.display()
  );
  Ok(())
}

fn file_name(path: &Path) -> Result<OsString> {
  path
    .file_name()
    .map(OsStr::to_os_string)
    .with_context(|| format!("Path {} has no final component", path.display()))
}

fn proc_path(fd: &OwnedFd) -> PathBuf {
  PathBuf::from(format!("/proc/self/fd/{}", fd.as_raw_fd()))
}

fn metadata_fd(fd: &OwnedFd) -> Result<fs::Metadata> {
  fs::metadata(proc_path(fd))
    .context("Failed to inspect open filesystem object")
}

#[cfg(test)]
mod tests {
  use std::os::unix::fs::{PermissionsExt, symlink};

  use super::*;

  fn entry(
    store: &str,
    source: &str,
    target: &str,
    kind: Kind,
    method: Method,
  ) -> Entry {
    Entry {
      store: PathBuf::from(store),
      source: PathBuf::from(source),
      target: PathBuf::from(target),
      kind,
      method,
      owner: None,
      group: None,
      mode: Some("0750".into()),
      parent_owner: None,
      parent_group: None,
      parent_mode: None,
    }
  }

  #[test]
  fn creates_files_and_safe_symlinks_under_an_alternate_root() {
    let temporary = tempfile::tempdir().unwrap();
    fs::create_dir(temporary.path().join("persist")).unwrap();
    let root = Root::open(temporary.path()).unwrap();
    let entry = entry(
      "/persist",
      "/persist/etc/token",
      "/etc/token",
      Kind::File,
      Method::Symlink,
    );

    prepare(&root, std::slice::from_ref(&entry)).unwrap();
    link(&root, &entry).unwrap();

    assert!(temporary.path().join("persist/etc/token").is_file());
    assert_eq!(
      fs::read_link(temporary.path().join("etc/token")).unwrap(),
      Path::new("/persist/etc/token")
    );
    assert_eq!(
      fs::metadata(temporary.path().join("persist/etc/token"))
        .unwrap()
        .permissions()
        .mode()
        & 0o7777,
      0o750
    );
  }

  #[test]
  fn rejects_store_overlap_and_nested_symlink_targets() {
    let mut overlap = vec![entry(
      "/persist",
      "/persist/state",
      "/persist/nested",
      Kind::Directory,
      Method::Bind,
    )];
    assert!(validate_and_sort(&mut overlap).is_err());

    let mut nested = vec![
      entry(
        "/persist",
        "/persist/a",
        "/var/lib",
        Kind::Directory,
        Method::Symlink,
      ),
      entry(
        "/persist",
        "/persist/b",
        "/var/lib/app",
        Kind::Directory,
        Method::Bind,
      ),
    ];
    assert!(validate_and_sort(&mut nested).is_err());
  }

  #[test]
  fn refuses_to_traverse_intermediate_symlinks() {
    let temporary = tempfile::tempdir().unwrap();
    fs::create_dir(temporary.path().join("outside")).unwrap();
    symlink(
      temporary.path().join("outside"),
      temporary.path().join("persist"),
    )
    .unwrap();
    let root = Root::open(temporary.path()).unwrap();
    let error = root
      .ensure_parent(Path::new("/persist/etc/token"))
      .unwrap_err();
    assert!(format!("{error:#}").contains("without following symlinks"));
    assert!(!temporary.path().join("outside/etc").exists());
  }

  #[test]
  fn reconciliation_removes_only_symlinks_owned_by_the_old_plan() {
    let temporary = tempfile::tempdir().unwrap();
    fs::create_dir_all(temporary.path().join("etc")).unwrap();
    let root = Root::open(temporary.path()).unwrap();
    let old = entry(
      "/persist",
      "/persist/etc/token",
      "/etc/token",
      Kind::File,
      Method::Symlink,
    );
    symlink(&old.source, temporary.path().join("etc/token")).unwrap();

    reconcile(&root, std::slice::from_ref(&old), &[]).unwrap();
    assert!(fs::symlink_metadata(temporary.path().join("etc/token")).is_err());

    symlink("/somewhere/else", temporary.path().join("etc/token")).unwrap();
    reconcile(&root, &[old], &[]).unwrap();
    assert_eq!(
      fs::read_link(temporary.path().join("etc/token")).unwrap(),
      Path::new("/somewhere/else")
    );
  }
}
