use std::{
  collections::HashSet,
  ffi::{CString, OsStr, OsString},
  fs::{self, FileType},
  io::Write,
  os::{
    fd::{AsRawFd, OwnedFd},
    unix::{ffi::OsStrExt, fs::MetadataExt},
  },
  path::{Component, Path, PathBuf},
};

use anyhow::{Context, Result, bail, ensure};
use clap::Parser;
use log::info;
use nix::{
  errno::Errno,
  fcntl::{OFlag, open, openat, renameat},
  mount::{MntFlags, MsFlags, mount, umount2},
  sys::stat::{Mode, fchmod, mkdirat},
  unistd::{Gid, Group, Uid, UnlinkatFlags, User, fchown, symlinkat, unlinkat},
};
use serde::{Deserialize, Serialize};

#[derive(Parser, Debug)]
#[command(
  name = "persist",
  about = "Project persistent files and directories into a root"
)]
struct Args {
  /// JSON persistence plan generated by the NixOS module.
  #[arg(required_unless_present = "clear")]
  plan:    Option<PathBuf>,
  /// Root containing the plan's absolute source and target paths.
  #[arg(long, default_value = "/")]
  root:    PathBuf,
  /// Remove every projection recorded in the runtime state.
  #[arg(long)]
  clear:   bool,
  /// Validate and report the plan without changing the filesystem.
  #[arg(long)]
  dry_run: bool,
}

#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
struct Plan {
  version: u8,
  entries: Vec<Entry>,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
struct Entry {
  store:           PathBuf,
  source:          PathBuf,
  target:          PathBuf,
  kind:            Kind,
  method:          Method,
  #[serde(default = "default_true")]
  manage_metadata: bool,
  /// Whether this run or a recorded one created the bind target, so removal
  /// may take it away again.
  #[serde(default)]
  placeholder:     bool,
  #[serde(default)]
  owner:           Option<String>,
  #[serde(default)]
  group:           Option<String>,
  #[serde(default)]
  mode:            Option<String>,
  #[serde(default)]
  parent_owner:    Option<String>,
  #[serde(default)]
  parent_group:    Option<String>,
  #[serde(default)]
  parent_mode:     Option<String>,
}

const fn default_true() -> bool {
  true
}

#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "lowercase")]
enum Kind {
  Directory,
  File,
}

#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "lowercase")]
enum Method {
  Bind,
  Symlink,
}

#[derive(Debug, Default, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
struct RuntimeState {
  version: u8,
  entries: Vec<Entry>,
}

struct Root {
  fd: OwnedFd,
}

#[derive(Debug)]
struct Node {
  fd:      OwnedFd,
  parent:  OwnedFd,
  created: bool,
}

#[derive(Debug)]
struct Dir {
  fd:      OwnedFd,
  created: bool,
}

#[derive(Default)]
struct DirDefaults<'a> {
  mirror:   Option<&'a Path>,
  metadata: bool,
}

const STATE_PATH: &str = "/run/nixos-core/persistence.json";

pub fn run(args: &[String]) -> Result<()> {
  let args = Args::parse_from(args);
  ensure!(
    args.root.is_absolute(),
    "Root {} is not absolute",
    args.root.display()
  );
  let root = Root::open(&args.root)?;
  let mut plan = match &args.plan {
    Some(path) if !args.clear => read_plan(path)?,
    _ => Vec::new(),
  };

  let state_path = Path::new(STATE_PATH);
  let mut previous = read_state(&root, state_path)?.entries;
  inherit_placeholders(&mut plan, &previous);

  preflight(&root, &previous, &plan)?;

  if args.dry_run {
    for entry in &plan {
      info!(
        "would project {} at {}",
        entry.source.display(),
        entry.target.display()
      );
    }
    for entry in stale_entries(&previous, &plan) {
      info!("would remove projection at {}", entry.target.display());
    }
    return Ok(());
  }

  if let Err(error) = reconcile(&root, &previous, &plan) {
    return Err(rollback(
      error,
      project(&root, &mut previous, &mut Vec::new()),
    ));
  }
  let mut activated = Vec::new();
  let result = check_stores(&root, &plan)
    .and_then(|()| project(&root, &mut plan, &mut activated))
    .and_then(|()| write_state(&root, state_path, &plan));
  if let Err(error) = result {
    return Err(rollback(error, restore(&root, &mut previous, &activated)));
  }
  Ok(())
}

fn read_plan(path: &Path) -> Result<Vec<Entry>> {
  let raw = fs::read(path)
    .with_context(|| format!("Failed to read {}", path.display()))?;
  let mut plan: Plan = serde_json::from_slice(&raw)
    .with_context(|| format!("Failed to parse {}", path.display()))?;
  ensure!(
    plan.version == 1,
    "Unsupported persistence plan version {}",
    plan.version
  );
  validate_and_sort(&mut plan.entries)?;
  Ok(plan.entries)
}

fn inherit_placeholders(plan: &mut [Entry], previous: &[Entry]) {
  for entry in plan {
    entry.placeholder = previous
      .iter()
      .any(|old| old.placeholder && same_projection(old, entry));
  }
}

fn rollback(error: anyhow::Error, restored: Result<()>) -> anyhow::Error {
  match restored {
    Ok(()) => error,
    Err(restore_error) => {
      error.context(format!(
        "Restoring the previous persistence plan also failed \
         ({restore_error:#})"
      ))
    },
  }
}

fn validate_and_sort(entries: &mut [Entry]) -> Result<()> {
  let mut sources = HashSet::new();
  let mut targets = HashSet::new();
  let stores = entries
    .iter()
    .map(|entry| &entry.store)
    .collect::<HashSet<_>>();

  for entry in entries.iter() {
    validate_absolute(&entry.store, "store")?;
    validate_absolute(&entry.source, "source")?;
    validate_absolute(&entry.target, "target")?;
    ensure!(
      entry.store != Path::new("/"),
      "The persistence store cannot be /"
    );
    ensure!(
      entry.target != Path::new("/"),
      "The persistence target cannot be /"
    );
    ensure!(
      entry.source.starts_with(&entry.store) && entry.source != entry.store,
      "Source {} is not below store {}",
      entry.source.display(),
      entry.store.display()
    );
    ensure!(
      sources.insert(&entry.source),
      "Duplicate source {}",
      entry.source.display()
    );
    ensure!(
      targets.insert(&entry.target),
      "Duplicate target {}",
      entry.target.display()
    );
    for store in &stores {
      ensure!(
        !paths_overlap(&entry.target, store),
        "Persistence target {} overlaps store {}",
        entry.target.display(),
        store.display()
      );
    }
    let state_dir = Path::new(STATE_PATH)
      .parent()
      .expect("state path has a parent");
    for path in [&entry.source, &entry.target] {
      ensure!(
        !paths_overlap(path, state_dir),
        "Path {} overlaps the runtime state directory {}",
        path.display(),
        state_dir.display()
      );
    }
    for mode in [entry.mode.as_deref(), entry.parent_mode.as_deref()]
      .into_iter()
      .flatten()
    {
      parse_mode(mode)?;
    }
  }

  for parent in entries
    .iter()
    .filter(|entry| entry.method == Method::Symlink)
  {
    if let Some(child) = entries.iter().find(|entry| {
      entry.target != parent.target && entry.target.starts_with(&parent.target)
    }) {
      bail!(
        "Target {} is nested below symlink target {}",
        child.target.display(),
        parent.target.display()
      );
    }
  }

  entries.sort_by(|left, right| {
    left
      .target
      .components()
      .count()
      .cmp(&right.target.components().count())
      .then_with(|| left.target.cmp(&right.target))
  });
  Ok(())
}

fn paths_overlap(left: &Path, right: &Path) -> bool {
  left.starts_with(right) || right.starts_with(left)
}

fn validate_absolute(path: &Path, label: &str) -> Result<()> {
  ensure!(
    path.is_absolute(),
    "{label} path {} is not absolute",
    path.display()
  );
  ensure!(
    path
      .components()
      .all(|part| matches!(part, Component::RootDir | Component::Normal(_))),
    "{label} path {} is not normalized",
    path.display()
  );
  Ok(())
}

fn preflight(root: &Root, previous: &[Entry], current: &[Entry]) -> Result<()> {
  check_stores(root, current)?;
  let removed = removal_order(previous, current);
  for entry in current {
    root.inspect_node(&entry.source, entry.kind, "source")?;
    resolve_metadata(entry)?;
    let untouched = !removed
      .iter()
      .any(|old| paths_overlap(&old.target, &entry.target));
    if untouched {
      preflight_target(root, entry)?;
    }
  }
  for entry in removed {
    preflight_removal(root, entry)?;
  }
  Ok(())
}

fn preflight_target(root: &Root, entry: &Entry) -> Result<()> {
  match entry.method {
    Method::Bind => {
      let Some(target) =
        root.inspect_node(&entry.target, entry.kind, "target")?
      else {
        return Ok(());
      };
      if !is_mount_node(&target) {
        return Ok(());
      }
      let source = root.open_node(&entry.source, entry.kind)?;
      ensure!(
        source
          .is_some_and(|source| same_node(&source, &target).unwrap_or(false)),
        "Target {} is already a different mount",
        entry.target.display()
      );
      Ok(())
    },
    Method::Symlink => {
      let Some((parent, name)) =
        root.existing_parent_and_name(&entry.target)?
      else {
        return Ok(());
      };
      match fs::symlink_metadata(proc_path(&parent).join(&name)) {
        Ok(metadata) if metadata.file_type().is_symlink() => {
          owned_symlink(root, entry)?.map(drop).with_context(|| {
            format!(
              "Symlink {} does not point to {}",
              entry.target.display(),
              entry.source.display()
            )
          })
        },
        Ok(_) => {
          bail!(
            "Refusing to replace existing target {} with a symlink",
            entry.target.display()
          )
        },
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => Ok(()),
        Err(error) => {
          Err(error).with_context(|| {
            format!("Failed to inspect {}", entry.target.display())
          })
        },
      }
    },
  }
}

fn check_stores(root: &Root, entries: &[Entry]) -> Result<()> {
  for entry in entries {
    ensure!(
      root.open_node(&entry.store, Kind::Directory)?.is_some(),
      "Persistence store {} does not exist",
      entry.store.display()
    );
    ensure!(
      root.is_mounted(&entry.store)?,
      "Persistence store {} is not on a mounted filesystem",
      entry.store.display()
    );
  }
  Ok(())
}

fn project(
  root: &Root,
  entries: &mut [Entry],
  activated: &mut Vec<Entry>,
) -> Result<()> {
  for entry in entries {
    prepare(root, entry)?;
    activate(root, std::slice::from_ref(entry), activated)?;
  }
  Ok(())
}

fn prepare(root: &Root, entry: &mut Entry) -> Result<()> {
  let source_parent = root.ensure_parent(&entry.source, &DirDefaults {
    mirror:   entry.target.parent(),
    metadata: entry.manage_metadata,
  })?;
  if source_parent.created {
    root.discard_on_error(
      parent_of(&entry.source),
      Kind::Directory,
      apply_parent_metadata(entry, &source_parent.fd, &entry.source),
    )?;
  }
  let source = root.create_node(&entry.source, entry.kind, "source")?;
  if source.created {
    root.discard_on_error(
      &entry.source,
      entry.kind,
      apply_entry_metadata(entry, &source.fd),
    )?;
  }

  let target_parent = root.ensure_parent(&entry.target, &DirDefaults {
    mirror:   entry.source.parent().filter(|_| entry.manage_metadata),
    metadata: true,
  })?;
  if target_parent.created {
    root.discard_on_error(
      parent_of(&entry.target),
      Kind::Directory,
      apply_parent_metadata(entry, &target_parent.fd, &entry.target),
    )?;
  }
  if entry.method == Method::Bind {
    let target = root.create_node(&entry.target, entry.kind, "target")?;
    if target.created {
      let template = if entry.manage_metadata {
        &source.fd
      } else {
        &target_parent.fd
      };
      root.discard_on_error(
        &entry.target,
        entry.kind,
        copy_metadata(template, &target.fd),
      )?;
      entry.placeholder = true;
    }
  }
  Ok(())
}

fn parent_of(path: &Path) -> &Path {
  path.parent().expect("validated path has a parent")
}

fn activate(
  root: &Root,
  entries: &[Entry],
  activated: &mut Vec<Entry>,
) -> Result<()> {
  for entry in entries {
    let changed = match entry.method {
      Method::Bind => bind(root, entry)?,
      Method::Symlink => link(root, entry)?,
    };
    if changed {
      activated.push(entry.clone());
    }
  }
  Ok(())
}

fn restore(
  root: &Root,
  previous: &mut [Entry],
  activated: &[Entry],
) -> Result<()> {
  reconcile(root, activated, &[])?;
  project(root, previous, &mut Vec::new())
}

fn read_state(root: &Root, path: &Path) -> Result<RuntimeState> {
  let Some(node) = root.open_node(path, Kind::File)? else {
    return Ok(RuntimeState {
      version: 1,
      entries: Vec::new(),
    });
  };
  let raw = fs::read(proc_path(&node.fd)).with_context(|| {
    format!("Failed to read runtime state {}", path.display())
  })?;
  let mut state: RuntimeState =
    serde_json::from_slice(&raw).with_context(|| {
      format!("Failed to parse runtime state {}", path.display())
    })?;
  ensure!(
    state.version == 1,
    "Unsupported persistence runtime state version {}",
    state.version
  );
  validate_and_sort(&mut state.entries)?;
  Ok(state)
}

fn stale_entries<'a>(
  previous: &'a [Entry],
  current: &[Entry],
) -> Vec<&'a Entry> {
  previous
    .iter()
    .filter(|old| !current.iter().any(|new| same_projection(old, new)))
    .collect()
}

fn reconcile(root: &Root, previous: &[Entry], current: &[Entry]) -> Result<()> {
  for entry in removal_order(previous, current) {
    match entry.method {
      Method::Bind => remove_bind(root, entry)?,
      Method::Symlink => remove_owned_symlink(root, entry)?,
    }
  }
  Ok(())
}

/// Stale entries plus everything projected below a bind that is going away
/// or arriving, since those would keep the parent busy or end up shadowed.
/// They get projected again afterwards.
fn removal_order<'a>(
  previous: &'a [Entry],
  current: &[Entry],
) -> Vec<&'a Entry> {
  let stale = stale_entries(previous, current);
  let added = current
    .iter()
    .filter(|new| !previous.iter().any(|old| same_projection(old, new)));
  let changing = stale
    .iter()
    .copied()
    .chain(added)
    .filter(|entry| entry.method == Method::Bind)
    .map(|entry| entry.target.as_path())
    .collect::<Vec<_>>();
  let mut removed = previous
    .iter()
    .filter(|entry| {
      stale.contains(entry)
        || changing.iter().any(|parent| {
          entry.target != *parent && entry.target.starts_with(parent)
        })
    })
    .collect::<Vec<_>>();
  removed
    .sort_by_key(|entry| std::cmp::Reverse(entry.target.components().count()));
  removed
}

fn preflight_removal(root: &Root, entry: &Entry) -> Result<()> {
  if entry.method == Method::Symlink {
    return owned_symlink(root, entry).map(drop);
  }
  let Some(target) = root.open_node(&entry.target, entry.kind)? else {
    return Ok(());
  };
  if is_mount_node(&target) {
    verify_projection_source(root, entry, &target)?;
  }
  Ok(())
}

fn remove_bind(root: &Root, entry: &Entry) -> Result<()> {
  let Some(target) = root.open_node(&entry.target, entry.kind)? else {
    return Ok(());
  };
  if !is_mount_node(&target) {
    return Ok(());
  }
  verify_projection_source(root, entry, &target)?;
  let Node { fd, parent, .. } = target;
  drop(fd);
  let name = file_name(&entry.target)?;
  umount2(&proc_path(&parent).join(&name), MntFlags::empty()).with_context(
    || {
      format!(
        "Failed to unmount stale projection {}",
        entry.target.display()
      )
    },
  )?;
  if !entry.placeholder {
    return Ok(());
  }
  let flags = match entry.kind {
    Kind::Directory => UnlinkatFlags::RemoveDir,
    Kind::File => UnlinkatFlags::NoRemoveDir,
  };
  match unlinkat(&parent, Path::new(&name), flags) {
    Ok(()) | Err(Errno::ENOENT | Errno::ENOTEMPTY) => Ok(()),
    Err(error) => {
      Err(error).with_context(|| {
        format!("Failed to remove placeholder {}", entry.target.display())
      })
    },
  }
}

fn verify_projection_source(
  root: &Root,
  entry: &Entry,
  target: &Node,
) -> Result<()> {
  let source =
    root
      .open_node(&entry.source, entry.kind)?
      .with_context(|| {
        format!("Cannot verify stale bind source {}", entry.source.display())
      })?;
  ensure!(
    same_node(&source, target)?,
    "Refusing to unmount {} because it no longer resolves to {}",
    entry.target.display(),
    entry.source.display()
  );
  Ok(())
}

fn same_projection(left: &Entry, right: &Entry) -> bool {
  left.source == right.source
    && left.target == right.target
    && left.kind == right.kind
    && left.method == right.method
}

fn is_mount_node(node: &Node) -> bool {
  match (mount_id(&node.fd), mount_id(&node.parent)) {
    (Some(node_id), Some(parent_id)) if node_id != parent_id => true,
    _ => {
      match (metadata_fd(&node.fd), metadata_fd(&node.parent)) {
        (Ok(node_metadata), Ok(parent_metadata)) => {
          node_metadata.dev() != parent_metadata.dev()
        },
        _ => false,
      }
    },
  }
}

fn mount_id(fd: &OwnedFd) -> Option<u64> {
  let fdinfo =
    fs::read_to_string(format!("/proc/self/fdinfo/{}", fd.as_raw_fd())).ok()?;
  fdinfo
    .lines()
    .find_map(|line| line.strip_prefix("mnt_id:\t")?.parse().ok())
}

fn owned_symlink(
  root: &Root,
  entry: &Entry,
) -> Result<Option<(OwnedFd, OsString)>> {
  let Some((parent, name)) = root.existing_parent_and_name(&entry.target)?
  else {
    return Ok(None);
  };
  match fs::read_link(proc_path(&parent).join(&name)) {
    Ok(existing) if existing == entry.source => Ok(Some((parent, name))),
    Ok(_) => Ok(None),
    Err(error)
      if matches!(
        error.kind(),
        std::io::ErrorKind::NotFound | std::io::ErrorKind::InvalidInput
      ) =>
    {
      Ok(None)
    },
    Err(error) => {
      Err(error).with_context(|| {
        format!("Failed to inspect {}", entry.target.display())
      })
    },
  }
}

fn remove_owned_symlink(root: &Root, entry: &Entry) -> Result<()> {
  let Some((parent, name)) = owned_symlink(root, entry)? else {
    return Ok(());
  };

  let quarantine =
    OsString::from(format!(".nixos-core-stale-{}", std::process::id()));
  rename_noreplace(&parent, Path::new(&name), &parent, Path::new(&quarantine))
    .with_context(|| {
      format!(
        "Failed to quarantine stale symlink {}",
        entry.target.display()
      )
    })?;
  let quarantined = proc_path(&parent).join(&quarantine);
  match fs::read_link(&quarantined) {
    Ok(source) if source == entry.source => {
      unlinkat(&parent, Path::new(&quarantine), UnlinkatFlags::NoRemoveDir)
        .with_context(|| {
          format!("Failed to remove stale symlink {}", entry.target.display())
        })
    },
    result => {
      rename_noreplace(
        &parent,
        Path::new(&quarantine),
        &parent,
        Path::new(&name),
      )
      .with_context(|| {
        format!(
          "Target {} changed while it was being reconciled",
          entry.target.display()
        )
      })?;
      match result {
        Ok(_) => {
          bail!(
            "Target {} changed while it was being reconciled",
            entry.target.display()
          )
        },
        Err(error) => {
          Err(error).with_context(|| {
            format!("Failed to inspect {}", entry.target.display())
          })
        },
      }
    },
  }
}

fn write_state(root: &Root, path: &Path, entries: &[Entry]) -> Result<()> {
  let parent = root.ensure_parent(path, &DirDefaults::default())?.fd;
  let name = file_name(path)?;
  let temporary = OsString::from(format!("{}.new", name.to_string_lossy()));
  let raw = serde_json::to_vec(&RuntimeState {
    version: 1,
    entries: entries.to_vec(),
  })
  .context("Failed to serialize persistence runtime state")?;
  let file = openat(
    &parent,
    Path::new(&temporary),
    OFlag::O_WRONLY
      | OFlag::O_CREAT
      | OFlag::O_TRUNC
      | OFlag::O_NOFOLLOW
      | OFlag::O_CLOEXEC,
    Mode::from_bits_truncate(0o644),
  )
  .map(fs::File::from)
  .with_context(|| {
    format!(
      "Failed to create temporary runtime state for {}",
      path.display()
    )
  })?;
  (&file).write_all(&raw).with_context(|| {
    format!(
      "Failed to write temporary runtime state for {}",
      path.display()
    )
  })?;
  drop(file);
  renameat(&parent, Path::new(&temporary), &parent, Path::new(&name))
    .with_context(|| {
      format!("Failed to commit runtime state {}", path.display())
    })
}

fn rename_noreplace(
  old_parent: &OwnedFd,
  old_name: &Path,
  new_parent: &OwnedFd,
  new_name: &Path,
) -> Result<()> {
  let old_name = CString::new(old_name.as_os_str().as_bytes())
    .context("Old rename path contains a NUL byte")?;
  let new_name = CString::new(new_name.as_os_str().as_bytes())
    .context("New rename path contains a NUL byte")?;
  // SAFETY: both path pointers are live NUL-terminated strings, and both file
  // descriptors remain owned for the duration of the syscall.
  let result = unsafe {
    libc::syscall(
      libc::SYS_renameat2,
      old_parent.as_raw_fd(),
      old_name.as_ptr(),
      new_parent.as_raw_fd(),
      new_name.as_ptr(),
      libc::RENAME_NOREPLACE,
    )
  };
  Errno::result(result).map(drop).map_err(Into::into)
}

fn resolve_metadata(entry: &Entry) -> Result<()> {
  for value in [entry.owner.as_deref(), entry.parent_owner.as_deref()] {
    resolve_user(value)?;
  }
  for value in [entry.group.as_deref(), entry.parent_group.as_deref()] {
    resolve_group(value)?;
  }
  Ok(())
}

fn apply_entry_metadata(entry: &Entry, fd: &OwnedFd) -> Result<()> {
  apply_metadata(
    fd,
    entry.owner.as_deref(),
    entry.group.as_deref(),
    entry.mode.as_deref(),
    &entry.source,
  )
}

fn apply_parent_metadata(
  entry: &Entry,
  fd: &OwnedFd,
  path: &Path,
) -> Result<()> {
  apply_metadata(
    fd,
    entry.parent_owner.as_deref(),
    entry.parent_group.as_deref(),
    entry.parent_mode.as_deref(),
    path.parent().expect("validated path has a parent"),
  )
}

fn apply_metadata(
  fd: &OwnedFd,
  owner: Option<&str>,
  group: Option<&str>,
  mode: Option<&str>,
  display_path: &Path,
) -> Result<()> {
  let uid = resolve_user(owner)?.map(Uid::from_raw);
  let gid = resolve_group(group)?.map(Gid::from_raw);
  if uid.is_some() || gid.is_some() {
    fchown(fd, uid, gid)
      .with_context(|| format!("Failed to chown {}", display_path.display()))?;
  }
  if let Some(mode) = mode {
    fchmod(fd, Mode::from_bits_truncate(parse_mode(mode)?))
      .with_context(|| format!("Failed to chmod {}", display_path.display()))?;
  }
  Ok(())
}

fn copy_metadata(from: &OwnedFd, to: &OwnedFd) -> Result<()> {
  let metadata = metadata_fd(from)?;
  fchown(
    to,
    Some(Uid::from_raw(metadata.uid())),
    Some(Gid::from_raw(metadata.gid())),
  )
  .context("Failed to copy ownership")?;
  fchmod(to, Mode::from_bits_truncate(metadata.mode() & 0o7777))
    .context("Failed to copy mode")
}

fn parse_mode(mode: &str) -> Result<u32> {
  let parsed = u32::from_str_radix(mode, 8)
    .with_context(|| format!("Invalid octal mode {mode:?}"))?;
  ensure!(parsed <= 0o7777, "Mode {mode:?} exceeds 07777");
  Ok(parsed)
}

fn resolve_user(value: Option<&str>) -> Result<Option<u32>> {
  let Some(value) = value else { return Ok(None) };
  if let Ok(id) = value.parse() {
    return Ok(Some(id));
  }
  let user = User::from_name(value)
    .with_context(|| format!("Failed to resolve user {value}"))?;
  match user {
    Some(user) => Ok(Some(user.uid.as_raw())),
    None => bail!("User {value} does not exist"),
  }
}

fn resolve_group(value: Option<&str>) -> Result<Option<u32>> {
  let Some(value) = value else { return Ok(None) };
  if let Ok(id) = value.parse() {
    return Ok(Some(id));
  }
  let group = Group::from_name(value)
    .with_context(|| format!("Failed to resolve group {value}"))?;
  match group {
    Some(group) => Ok(Some(group.gid.as_raw())),
    None => bail!("Group {value} does not exist"),
  }
}

fn bind(root: &Root, entry: &Entry) -> Result<bool> {
  let source =
    root
      .open_node(&entry.source, entry.kind)?
      .with_context(|| {
        format!("Source {} disappeared", entry.source.display())
      })?;
  let target =
    root
      .open_node(&entry.target, entry.kind)?
      .with_context(|| {
        format!("Target {} disappeared", entry.target.display())
      })?;
  if same_node(&source, &target)? {
    return Ok(false);
  }
  ensure!(
    !is_mount_node(&target),
    "Target {} is already a different mount",
    entry.target.display()
  );
  let source_path = proc_path(&source.fd);
  let target_path = proc_path(&target.fd);
  mount(
    Some(source_path.as_path()),
    target_path.as_path(),
    None::<&str>,
    MsFlags::MS_BIND,
    None::<&str>,
  )
  .with_context(|| {
    format!(
      "Failed to bind {} at {}",
      entry.source.display(),
      entry.target.display()
    )
  })?;
  let verified = root
    .open_node(&entry.target, entry.kind)?
    .with_context(|| {
      format!("Target {} disappeared after mount", entry.target.display())
    })
    .and_then(|mounted| {
      ensure!(
        same_node(&source, &mounted)?,
        "Bind mount at {} did not resolve to {}",
        entry.target.display(),
        entry.source.display()
      );
      Ok(())
    });
  if let Err(error) = verified {
    drop(target);
    let _ = umount2(&target_path, MntFlags::empty());
    return Err(error);
  }
  Ok(true)
}

fn same_node(source: &Node, target: &Node) -> Result<bool> {
  let source = metadata_fd(&source.fd)?;
  let target = metadata_fd(&target.fd)?;
  Ok(source.dev() == target.dev() && source.ino() == target.ino())
}

fn link(root: &Root, entry: &Entry) -> Result<bool> {
  let (parent, name) = root
    .existing_parent_and_name(&entry.target)?
    .with_context(|| {
      format!("Parent of {} does not exist", entry.target.display())
    })?;
  let path = proc_path(&parent).join(&name);
  match fs::symlink_metadata(&path) {
    Ok(metadata) if metadata.file_type().is_symlink() => {
      let existing = fs::read_link(&path).with_context(|| {
        format!("Failed to read {}", entry.target.display())
      })?;
      ensure!(
        existing == entry.source,
        "Symlink {} points to {}, expected {}",
        entry.target.display(),
        existing.display(),
        entry.source.display()
      );
      Ok(false)
    },
    Ok(_) => {
      bail!(
        "Refusing to replace existing target {} with a symlink",
        entry.target.display()
      )
    },
    Err(error) if error.kind() == std::io::ErrorKind::NotFound => {
      symlinkat(&entry.source, &parent, Path::new(&name)).with_context(
        || {
          format!(
            "Failed to link {} to {}",
            entry.target.display(),
            entry.source.display()
          )
        },
      )?;
      Ok(true)
    },
    Err(error) => {
      Err(error).with_context(|| {
        format!("Failed to inspect {}", entry.target.display())
      })
    },
  }
}

impl Root {
  fn open(path: &Path) -> Result<Self> {
    let fd = open(
      path,
      OFlag::O_RDONLY | OFlag::O_DIRECTORY | OFlag::O_CLOEXEC,
      Mode::empty(),
    )
    .with_context(|| format!("Failed to open root {}", path.display()))?;
    Ok(Self { fd })
  }

  fn is_mounted(&self, path: &Path) -> Result<bool> {
    for ancestor in path.ancestors().filter(|part| part.parent().is_some()) {
      if let Some(node) = self.open_node(ancestor, Kind::Directory)?
        && is_mount_node(&node)
      {
        return Ok(true);
      }
    }
    Ok(false)
  }

  fn inspect_node(
    &self,
    path: &Path,
    kind: Kind,
    label: &str,
  ) -> Result<Option<Node>> {
    let node = self.open_node(path, kind)?;
    if let Some(node) = &node {
      ensure_kind(path, metadata_fd(&node.fd)?.file_type(), kind, label)?;
    }
    Ok(node)
  }

  fn create_node(&self, path: &Path, kind: Kind, label: &str) -> Result<Node> {
    if let Some(node) = self.open_node(path, kind)? {
      ensure_kind(path, metadata_fd(&node.fd)?.file_type(), kind, label)?;
      return Ok(node);
    }
    let parent_path = path.parent().expect("validated path has a parent");
    let parent = self.open_dir(parent_path)?.with_context(|| {
      format!("Parent of {label} {} does not exist", path.display())
    })?;
    let name = file_name(path)?;
    match kind {
      Kind::Directory => {
        mkdirat(&parent, Path::new(&name), Mode::from_bits_truncate(0o755))
      },
      Kind::File => {
        openat(
          &parent,
          Path::new(&name),
          OFlag::O_RDONLY
            | OFlag::O_CREAT
            | OFlag::O_EXCL
            | OFlag::O_NOFOLLOW
            | OFlag::O_CLOEXEC,
          Mode::from_bits_truncate(0o600),
        )
        .map(drop)
      },
    }
    .with_context(|| format!("Failed to create {label} {}", path.display()))?;
    let mut node = self.open_node(path, kind)?.with_context(|| {
      format!("Created {label} {} disappeared", path.display())
    })?;
    node.created = true;
    Ok(node)
  }

  fn open_node(&self, path: &Path, kind: Kind) -> Result<Option<Node>> {
    let parent_path = path.parent().expect("validated path has a parent");
    let Some(parent) = self.open_dir(parent_path)? else {
      return Ok(None);
    };
    let name = file_name(path)?;
    // O_NONBLOCK keeps a FIFO planted at a file entry from stalling the open.
    let mut flags = OFlag::O_RDONLY
      | OFlag::O_NOFOLLOW
      | OFlag::O_NONBLOCK
      | OFlag::O_CLOEXEC;
    if kind == Kind::Directory {
      flags |= OFlag::O_DIRECTORY;
    }
    match openat(&parent, Path::new(&name), flags, Mode::empty()) {
      Ok(fd) => {
        Ok(Some(Node {
          fd,
          parent,
          created: false,
        }))
      },
      Err(Errno::ENOENT) => Ok(None),
      Err(error) => {
        Err(error).with_context(|| {
          format!(
            "Failed to open {} without following symlinks",
            path.display()
          )
        })
      },
    }
  }

  fn ensure_parent(&self, path: &Path, defaults: &DirDefaults) -> Result<Dir> {
    let parent = path.parent().expect("validated path has a parent");
    self
      .walk(parent, Some(defaults))?
      .with_context(|| format!("Failed to create parent {}", parent.display()))
  }

  fn existing_parent_and_name(
    &self,
    path: &Path,
  ) -> Result<Option<(OwnedFd, OsString)>> {
    let parent = path.parent().expect("validated path has a parent");
    Ok(self.open_dir(parent)?.map(|fd| {
      (
        fd,
        file_name(path).expect("validated path has a final component"),
      )
    }))
  }

  fn open_dir(&self, path: &Path) -> Result<Option<OwnedFd>> {
    Ok(self.walk(path, None)?.map(|dir| dir.fd))
  }

  fn walk(
    &self,
    path: &Path,
    create: Option<&DirDefaults>,
  ) -> Result<Option<Dir>> {
    let mut current = self
      .fd
      .try_clone()
      .context("Failed to duplicate root descriptor")?;
    let mut created = false;
    let names = path
      .components()
      .filter_map(|component| {
        match component {
          Component::Normal(name) => Some(name),
          _ => None,
        }
      })
      .collect::<Vec<_>>();
    for (index, name) in names.iter().enumerate() {
      let flags = OFlag::O_RDONLY
        | OFlag::O_DIRECTORY
        | OFlag::O_NOFOLLOW
        | OFlag::O_CLOEXEC;
      match openat(&current, Path::new(name), flags, Mode::empty()) {
        Ok(next) => {
          current = next;
          created = false;
        },
        Err(Errno::ENOENT) => {
          let Some(defaults) = create else {
            return Ok(None);
          };
          match mkdirat(
            &current,
            Path::new(name),
            Mode::from_bits_truncate(0o755),
          ) {
            Ok(()) | Err(Errno::EEXIST) => {},
            Err(error) => {
              return Err(error).with_context(|| {
                format!("Failed to create {}", path.display())
              });
            },
          }
          let next = openat(&current, Path::new(name), flags, Mode::empty())
            .with_context(|| {
              format!(
                "Failed to open newly created directory {}",
                path.display()
              )
            })?;
          let applied = self.apply_dir_defaults(
            &next,
            &current,
            name,
            defaults,
            names.len() - index - 1,
          );
          if let Err(error) = applied {
            drop(next);
            return Err(discard_failure(
              error,
              unlinkat(&current, Path::new(name), UnlinkatFlags::RemoveDir),
              path,
            ));
          }
          current = next;
          created = true;
        },
        Err(error) => {
          return Err(error).with_context(|| {
            format!(
              "Failed to traverse {} without following symlinks",
              path.display()
            )
          });
        },
      }
    }
    Ok(Some(Dir {
      fd: current,
      created,
    }))
  }

  fn discard_on_error(
    &self,
    path: &Path,
    kind: Kind,
    result: Result<()>,
  ) -> Result<()> {
    let Err(error) = result else { return Ok(()) };
    let removed = self.existing_parent_and_name(path).and_then(|found| {
      let (parent, name) = found.context("Parent disappeared")?;
      let flags = match kind {
        Kind::Directory => UnlinkatFlags::RemoveDir,
        Kind::File => UnlinkatFlags::NoRemoveDir,
      };
      unlinkat(&parent, Path::new(&name), flags).map_err(Into::into)
    });
    Err(discard_failure(error, removed, path))
  }

  fn apply_dir_defaults(
    &self,
    dir: &OwnedFd,
    parent: &OwnedFd,
    name: &OsStr,
    defaults: &DirDefaults,
    strip: usize,
  ) -> Result<()> {
    if !defaults.metadata {
      return Ok(());
    }
    let mirror = defaults
      .mirror
      .and_then(|mirror| mirror.ancestors().nth(strip))
      .filter(|mirror| mirror.file_name() == Some(name));
    if let Some(mirror) = mirror
      && let Some(node) = self.open_node(mirror, Kind::Directory).ok().flatten()
    {
      return copy_metadata(&node.fd, dir);
    }
    let owner = metadata_fd(parent)?;
    fchown(
      dir,
      Some(Uid::from_raw(owner.uid())),
      Some(Gid::from_raw(owner.gid())),
    )
    .context("Failed to chown created directory")
  }
}

fn discard_failure<E: Into<anyhow::Error>>(
  error: anyhow::Error,
  removed: std::result::Result<(), E>,
  path: &Path,
) -> anyhow::Error {
  match removed {
    Ok(()) => error,
    Err(remove_error) => {
      error.context(format!(
        "Left {} behind because removing it failed ({:#})",
        path.display(),
        remove_error.into()
      ))
    },
  }
}

fn ensure_kind(
  path: &Path,
  file_type: FileType,
  kind: Kind,
  label: &str,
) -> Result<()> {
  let matches = match kind {
    Kind::Directory => file_type.is_dir(),
    Kind::File => file_type.is_file(),
  };
  ensure!(
    matches,
    "Existing {label} {} has the wrong type",
    path.display()
  );
  Ok(())
}

fn file_name(path: &Path) -> Result<OsString> {
  path
    .file_name()
    .map(OsStr::to_os_string)
    .with_context(|| format!("Path {} has no final component", path.display()))
}

fn proc_path(fd: &OwnedFd) -> PathBuf {
  PathBuf::from(format!("/proc/self/fd/{}", fd.as_raw_fd()))
}

fn metadata_fd(fd: &OwnedFd) -> Result<fs::Metadata> {
  fs::metadata(proc_path(fd))
    .context("Failed to inspect open filesystem object")
}

#[cfg(test)]
mod tests {
  use std::os::unix::fs::{PermissionsExt, symlink};

  use super::*;

  fn entry(
    store: &str,
    source: &str,
    target: &str,
    kind: Kind,
    method: Method,
  ) -> Entry {
    Entry {
      store: PathBuf::from(store),
      source: PathBuf::from(source),
      target: PathBuf::from(target),
      kind,
      method,
      manage_metadata: true,
      placeholder: false,
      owner: None,
      group: None,
      mode: Some("0750".into()),
      parent_owner: None,
      parent_group: None,
      parent_mode: None,
    }
  }

  fn mode_of(path: &Path) -> u32 {
    fs::metadata(path).unwrap().permissions().mode() & 0o7777
  }

  #[test]
  fn creates_files_and_safe_symlinks_under_an_alternate_root() {
    let temporary = tempfile::tempdir().unwrap();
    fs::create_dir(temporary.path().join("persist")).unwrap();
    let root = Root::open(temporary.path()).unwrap();
    let mut entry = entry(
      "/persist",
      "/persist/etc/token",
      "/etc/token",
      Kind::File,
      Method::Symlink,
    );

    prepare(&root, &mut entry).unwrap();
    link(&root, &entry).unwrap();

    assert!(temporary.path().join("persist/etc/token").is_file());
    assert_eq!(
      fs::read_link(temporary.path().join("etc/token")).unwrap(),
      Path::new("/persist/etc/token")
    );
    assert_eq!(mode_of(&temporary.path().join("persist/etc/token")), 0o750);
  }

  #[test]
  fn metadata_only_applies_to_objects_it_created() {
    let temporary = tempfile::tempdir().unwrap();
    fs::create_dir(temporary.path().join("persist")).unwrap();
    let root = Root::open(temporary.path()).unwrap();
    let mut entry = entry(
      "/persist",
      "/persist/var/state",
      "/var/state",
      Kind::Directory,
      Method::Symlink,
    );

    prepare(&root, &mut entry).unwrap();
    assert_eq!(mode_of(&temporary.path().join("persist/var/state")), 0o750);

    entry.mode = Some("0700".into());
    prepare(&root, &mut entry).unwrap();
    assert_eq!(mode_of(&temporary.path().join("persist/var/state")), 0o750);
  }

  #[test]
  fn created_parents_mirror_their_counterpart() {
    let temporary = tempfile::tempdir().unwrap();
    let home = temporary.path().join("home/alice");
    fs::create_dir_all(&home).unwrap();
    fs::set_permissions(&home, fs::Permissions::from_mode(0o700)).unwrap();
    fs::create_dir(temporary.path().join("persist")).unwrap();
    let root = Root::open(temporary.path()).unwrap();
    let mut entry = entry(
      "/persist",
      "/persist/home/alice/.local/state/app",
      "/home/alice/.local/state/app",
      Kind::Directory,
      Method::Symlink,
    );

    prepare(&root, &mut entry).unwrap();

    let persist = temporary.path().join("persist");
    assert_eq!(
      mode_of(&persist.join("home")),
      mode_of(&temporary.path().join("home"))
    );
    assert_eq!(mode_of(&persist.join("home/alice")), 0o700);
    assert_eq!(mode_of(&persist.join("home/alice/.local")), 0o755);
    assert_eq!(mode_of(&home.join(".local")), 0o755);
    assert_eq!(mode_of(&home.join(".local/state")), 0o755);
  }

  #[test]
  fn discards_created_objects_whose_metadata_fails() {
    if Uid::effective().is_root() {
      return;
    }
    let temporary = tempfile::tempdir().unwrap();
    fs::create_dir(temporary.path().join("persist")).unwrap();
    let root = Root::open(temporary.path()).unwrap();
    let mut entry = entry(
      "/persist",
      "/persist/var/state",
      "/var/state",
      Kind::Directory,
      Method::Symlink,
    );
    entry.owner = Some("0".into());

    assert!(prepare(&root, &mut entry).is_err());
    assert!(!temporary.path().join("persist/var/state").exists());

    entry.owner = None;
    prepare(&root, &mut entry).unwrap();
    assert_eq!(mode_of(&temporary.path().join("persist/var/state")), 0o750);
  }

  #[test]
  fn removes_binds_nested_below_a_stale_bind() {
    let parent = entry(
      "/persist",
      "/persist/a",
      "/target",
      Kind::Directory,
      Method::Bind,
    );
    let child = entry(
      "/cache",
      "/cache/b",
      "/target/child",
      Kind::Directory,
      Method::Bind,
    );
    let previous = vec![parent.clone(), child.clone()];

    let removed = removal_order(&previous, std::slice::from_ref(&child));
    assert_eq!(removed, vec![&child, &parent]);
    assert_eq!(
      removal_order(std::slice::from_ref(&child), &previous),
      vec![&child]
    );
    assert!(removal_order(&previous, &previous).is_empty());
  }

  #[test]
  fn placeholders_follow_unchanged_entries_between_runs() {
    let mut recorded = entry(
      "/persist",
      "/persist/a",
      "/target",
      Kind::Directory,
      Method::Bind,
    );
    recorded.placeholder = true;
    let mut plan = vec![recorded.clone(), recorded.clone()];
    plan[1].method = Method::Symlink;
    plan[1].placeholder = true;

    inherit_placeholders(&mut plan, std::slice::from_ref(&recorded));
    assert!(plan[0].placeholder);
    assert!(!plan[1].placeholder);
  }

  #[test]
  fn preflight_rejects_foreign_symlink_targets_it_will_not_replace() {
    let temporary = tempfile::tempdir().unwrap();
    fs::create_dir_all(temporary.path().join("persist/etc")).unwrap();
    fs::create_dir_all(temporary.path().join("etc")).unwrap();
    let root = Root::open(temporary.path()).unwrap();
    let entry = entry(
      "/persist",
      "/persist/etc/token",
      "/etc/token",
      Kind::File,
      Method::Symlink,
    );

    preflight_target(&root, &entry).unwrap();
    symlink(&entry.source, temporary.path().join("etc/token")).unwrap();
    preflight_target(&root, &entry).unwrap();
    fs::remove_file(temporary.path().join("etc/token")).unwrap();
    symlink("/somewhere/else", temporary.path().join("etc/token")).unwrap();
    assert!(preflight_target(&root, &entry).is_err());
    fs::remove_file(temporary.path().join("etc/token")).unwrap();
    fs::write(temporary.path().join("etc/token"), "plain").unwrap();
    assert!(preflight_target(&root, &entry).is_err());
  }

  #[test]
  fn rejects_paths_overlapping_the_runtime_state() {
    for target in ["/run", "/run/nixos-core/persistence.json"] {
      let mut entries = vec![entry(
        "/persist",
        "/persist/state",
        target,
        Kind::File,
        Method::Symlink,
      )];
      assert!(validate_and_sort(&mut entries).is_err());
    }
  }

  #[test]
  fn rejects_store_overlap_and_nested_symlink_targets() {
    let mut overlap = vec![entry(
      "/persist",
      "/persist/state",
      "/persist/nested",
      Kind::Directory,
      Method::Bind,
    )];
    assert!(validate_and_sort(&mut overlap).is_err());

    let mut nested = vec![
      entry(
        "/persist",
        "/persist/a",
        "/var/lib",
        Kind::Directory,
        Method::Symlink,
      ),
      entry(
        "/persist",
        "/persist/b",
        "/var/lib/app",
        Kind::Directory,
        Method::Bind,
      ),
    ];
    assert!(validate_and_sort(&mut nested).is_err());
  }

  #[test]
  fn refuses_to_traverse_intermediate_symlinks() {
    let temporary = tempfile::tempdir().unwrap();
    fs::create_dir(temporary.path().join("outside")).unwrap();
    symlink(
      temporary.path().join("outside"),
      temporary.path().join("persist"),
    )
    .unwrap();
    let root = Root::open(temporary.path()).unwrap();
    let error = root
      .ensure_parent(Path::new("/persist/etc/token"), &DirDefaults::default())
      .unwrap_err();
    assert!(format!("{error:#}").contains("without following symlinks"));
    assert!(!temporary.path().join("outside/etc").exists());
  }

  #[test]
  fn rejects_a_fifo_at_a_file_entry_without_blocking() {
    let temporary = tempfile::tempdir().unwrap();
    fs::create_dir(temporary.path().join("persist")).unwrap();
    nix::unistd::mkfifo(
      &temporary.path().join("persist/token"),
      Mode::from_bits_truncate(0o600),
    )
    .unwrap();
    let root = Root::open(temporary.path()).unwrap();
    let error = root
      .inspect_node(Path::new("/persist/token"), Kind::File, "source")
      .unwrap_err();
    assert!(format!("{error:#}").contains("wrong type"));
  }

  #[test]
  fn reconciliation_removes_only_symlinks_owned_by_the_old_plan() {
    let temporary = tempfile::tempdir().unwrap();
    fs::create_dir_all(temporary.path().join("etc")).unwrap();
    let root = Root::open(temporary.path()).unwrap();
    let old = entry(
      "/persist",
      "/persist/etc/token",
      "/etc/token",
      Kind::File,
      Method::Symlink,
    );
    symlink(&old.source, temporary.path().join("etc/token")).unwrap();

    reconcile(&root, std::slice::from_ref(&old), &[]).unwrap();
    assert!(fs::symlink_metadata(temporary.path().join("etc/token")).is_err());

    symlink("/somewhere/else", temporary.path().join("etc/token")).unwrap();
    preflight(&root, std::slice::from_ref(&old), &[]).unwrap();
    reconcile(&root, std::slice::from_ref(&old), &[]).unwrap();
    assert_eq!(
      fs::read_link(temporary.path().join("etc/token")).unwrap(),
      Path::new("/somewhere/else")
    );

    fs::remove_file(temporary.path().join("etc/token")).unwrap();
    fs::write(temporary.path().join("etc/token"), "plain").unwrap();
    preflight(&root, std::slice::from_ref(&old), &[]).unwrap();
    reconcile(&root, &[old], &[]).unwrap();
    assert!(temporary.path().join("etc/token").is_file());

    let long = "x".repeat(240);
    let old = entry(
      "/persist",
      "/persist/etc/long",
      &format!("/etc/{long}"),
      Kind::File,
      Method::Symlink,
    );
    symlink(&old.source, temporary.path().join("etc").join(&long)).unwrap();
    reconcile(&root, &[old], &[]).unwrap();
    assert!(
      fs::symlink_metadata(temporary.path().join("etc").join(&long)).is_err()
    );
  }
}
