[package]
name                   = "secrets"
description            = "age-compatible secrets manager with per-service isolation"
version.workspace      = true
edition.workspace      = true
rust-version.workspace = true
license.workspace      = true
repository.workspace   = true
readme                 = "README.md"

[dependencies]
age.workspace        = true
anyhow.workspace     = true
clap.workspace       = true
nix.workspace        = true
serde.workspace      = true
serde_json.workspace = true
tempfile.workspace   = true
zeroize.workspace    = true
